-- CreateTable
CREATE TABLE `t_site` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `slug` VARCHAR(50) NOT NULL,
    `nama` VARCHAR(100) NOT NULL,
    `badge_label` VARCHAR(20) NOT NULL,
    `badge_color` VARCHAR(20) NOT NULL,
    `geser_normal_max` DOUBLE NOT NULL,
    `geser_waspada_max` DOUBLE NOT NULL,
    `geser_siaga_max` DOUBLE NOT NULL,
    `laju_waspada_min` DOUBLE NOT NULL,
    `laju_siaga_min` DOUBLE NOT NULL,
    `laju_awas_min` DOUBLE NOT NULL,
    `rts_e` DOUBLE NULL,
    `rts_n` DOUBLE NULL,
    `rts_z` DOUBLE NULL,
    `utm_zone` INTEGER NOT NULL DEFAULT 50,
    `utm_north` BOOLEAN NOT NULL DEFAULT true,
    `map_lat` DOUBLE NULL,
    `map_lng` DOUBLE NULL,
    `map_zoom` INTEGER NOT NULL DEFAULT 16,
    `rotasi_deg` DOUBLE NULL,
    `pivot_e` DOUBLE NULL,
    `pivot_n` DOUBLE NULL,
    `ukur_e` DOUBLE NULL,
    `ukur_n` DOUBLE NULL,
    `pivot_lat` DOUBLE NULL,
    `pivot_lng` DOUBLE NULL,
    `ukur_lat` DOUBLE NULL,
    `ukur_lng` DOUBLE NULL,
    `terkalibrasi` BOOLEAN NOT NULL DEFAULT false,
    `aktif` BOOLEAN NOT NULL DEFAULT true,
    `urutan` INTEGER NOT NULL DEFAULT 0,
    `catatan` TEXT NULL,

    UNIQUE INDEX `t_site_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

